# Generated by Django 5.0.6 on 2024-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neutration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calaries',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protien',
            field=models.IntegerField(),
        ),
    ]
